#' Print function for gapclosing objects
#' @description Prints the same output as generated by \code{summary}
#' @param x An object of class \code{gapclosing}, which results from a call to the function \code{gapclosing}
#' @param ... Other arguments to \code{print} commands
#' @param digits Argument passed to print.data.frame
#' @param quote Argument passed to print.data.frame
#' @param right Argument passed to print.data.frame
#' @param row.names Argument passed to print.data.frame
#' @param max Argument passed to print.data.frame
#' @return Prints a summary of the estimates.
#' @references Lundberg, Ian. 2021. "The gap-closing estimand: A causal approach to study interventions that close disparities across social categories." {https://osf.io/gx4y3/}
#' @export

print.gapclosing <- function(
  x,
  ...,
  digits = 2,
  quote = FALSE,
  right = FALSE,
  row.names = FALSE,
  max = NULL
) {
  print(x$primary_estimate[,colnames(x$primary_estimate) != "setting"],
        digits = digits,
        quote = quote,
        right = right,
        row.names = row.names,
        max = max, scientific = F)
}
